telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

watson:
  assistant:
    key: ${WATSON_ASSISTANT_KEY}
    id: ${WATSON_ASSISTANT_ID}
  nlu:
    key: ${WATSON_NLU_KEY}
    
annotators: tokenize,cleanxml,ssplit,pos,lemma,ner,parse,depparse,coref,natlog,openie,kbp,entitylink